version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
  aws-oidc-role:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      # run the aws-cli/setup command from the orb
      # you need parameter below in steps "aws-cli/setup" for OIDC  
      - aws-cli/setup:
          # required parameter
          role-arn: $AWS_ROLE_ARN
          # optional parameters
          aws-region: AWS_DEFAULT_REGION   
          profile-name: "OIDC-PROFILE"
          role-session-name: "circleci-session"
          session-duration: "1800"
      - run:
          name: aws-s3-list-bucket
          command: |
            # must use same profile specified in the step above
            aws s3 ls --profile "OIDC-PROFILE"
        
    
workflows:
  raisetech:
    jobs:
      - cfn-lint
  OIDC-with-AWS:
    jobs:
      - aws-oidc-role:
          # must use a valid CircleCI context
          context: aws