version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1

parameters:
  profile-name:
    description: using it when you run aws-cli command
    type: string 
    default: oidc-profile
  role-session-name:
    description: using it when circleci assume role
    type: string 
    default: circleci-session
  vpc-stack-name:
    type: string 
    description: using it when CloudFormation creates the vpc stack
    default: test-vpc

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
  aws-oidc-create-stack:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      # run aws-cli/setup with the installed orb
      # you need parameter below in steps "aws-cli/setup" for OIDC token  
      - aws-cli/setup:
          # required parameter
          role-arn: $AWS_ROLE_ARN
          # optional parameters
          aws-region: AWS_DEFAULT_REGION   
          profile-name: <<parameters.profile-name>>
          role-session-name: <<parameters.role-session-name>>
          session-duration: "1800"
      - run:
          name: Create vpc stack
          command: |
            aws cloudformation create-stack \
            --stack-name <<parameters.vpc-stack-name>> \
            --template-body file://cloudformation/TestVPC.yml \
            --parameters ParameterKey=SystemName,ParameterValue=RT ParameterKey=Environment,ParameterValue=prod ParameterKey=CidrBlock,ParameterValue=10.4.0.0/16 \
            --profile <<parameters.profile-name>>
      - run:
          name: Wait until Stack is created
          command: |
            aws cloudformation wait stack-create-complete \
            --stack-name <<parameters.vpc-stack-name>>

workflows:
  cfn-test:
    jobs:
      - cfn-lint
      - aws-oidc-create-stack:
          # must use a valid CircleCI context if you need OIDC token
          context: aws
          requires:
            - cfn-lint
