# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  # See https://circleci.com/developer/orbs/orb/circleci/aws-cli
  aws-cli: circleci/aws-cli@3.1.5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  configure-role-arn:
    docker:
      - image: cimg/aws:2023.04    
    steps:
      - checkout  
      - aws-cli/setup:
          profile-name: default
      - aws-cli/role-arn-setup:
          profile-name: circleci-oidc
          role-arn: ${AWS_ROLE_ARN}
      - run:
          name: aws-sts-assume-role
          command: |
            aws_sts_credentials=$(aws sts assume-role-with-web-identity \
              --profile "circleci-oidc"
              --role-arn ${AWS_ROLE_ARN} \
              --web-identity-token ${CIRCLE_OIDC_TOKEN} \
              --role-session-name "circleci-oidc" \
              --duration-seconds 900 \
              --query "Credentials" \
              --output "json")
            echo export AWS_ACCESS_KEY_ID="$(echo $aws_sts_credentials | jq -r '.AccessKeyId')" >> $BASH_ENV
            echo export AWS_SECRET_ACCESS_KEY="$(echo $aws_sts_credentials | jq -r '.SecretAccessKey')" >> $BASH_ENV
            echo export AWS_SESSION_TOKEN="$(echo $aws_sts_credentials | jq -r '.SessionToken')" >> $BASH_ENV
            source $BASH_ENV              
workflows:
  aws-cli:
    jobs:
      - configure-role-arn:
          context: aws