version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
  aws-oidc-create-stack:
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      # run the aws-cli/setup command from the orb
      # you need parameter below in steps "aws-cli/setup" for OIDC  
      - aws-cli/setup:
          # required parameter
          role-arn: $AWS_ROLE_ARN
          # optional parameters
          aws-region: AWS_DEFAULT_REGION   
          profile-name: "OIDC-PROFILE"
          role-session-name: "circleci-session"
          session-duration: "1800"
      - run:
          name: Create stack of vpc
          command: |
            aws cloudformation create-stack \
            --stack-name test-vpc \
            --template-body file://cloudformation/TestVPC.yml \
            --parameters ParameterKey=SystemName,ParameterValue=RT ParameterKey=Environment,ParameterValue=prod ParameterKey=CidrBlock,ParameterValue=10.4.0.0/16 \
            --profile "OIDC-PROFILE"
      - run:
          name: Wait until Stack is created
          command: |
            aws cloudformation wait stack-create-complete \
            --stack-name test-vpc

workflows:
  cfn-test:
    jobs:
      - cfn-lint
      - aws-oidc-create-stack:
          # must use a valid CircleCI context if you need OIDC token
          context: aws
          requires:
            - cfn-lint
      # - aws-cfn-create-stack:
      #     context: aws
      #     requires:
      #       - aws-oidc-role
            