# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  # See https://circleci.com/developer/orbs/orb/circleci/aws-cli
  aws-cli: circleci/aws-cli@3.1.5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  configure-role-arn:
    executor: aws-cli/default
    steps:
      - checkout  
      - aws-cli/setup:
          profile-name: default
      - aws-cli/role-arn-setup:
          profile-name: WEB IDENTITY PROFILE
          role-arn: $AWS_ROLE_ARN
      - run:
          name: aws-sts-assume-role
          command: |
            aws sts assume-role-with-web-identity \
              --role-arn $AWS_ROLE_ARN \
              --web-identity-token $CIRCLE_OIDC_TOKEN \
              --role-session-name circleci-session \
              --duration-seconds 900 \
              --query "Credentials" \
              --output "json") 
workflows:
  aws-cli:
    jobs:
      - configure-role-arn