version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1

jobs:
  ## check CFn templates
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
  ## assume-role and create stacks
  aws-oidc-create-stack:
    #### define parameters #######################################################
    parameters:
      profile-name:
        description: using it when you run aws-cli command
        type: string 
        default: rt-oidc-profile
      role-session-name:
        description: using it when circleci assume role
        type: string 
        default: rt-circleci-session
      system-name:
        type: string 
        description: using it when CloudFormation creates the stack
        default: rt
      environment:
        type: enum
        description: using it when CloudFormation creates the stack
        enum: ["dev", "stg", "prod"]
      CidrBlock:
        type: string 
        description: using it when CloudFormation creates the stack
        default: 10.4.0.0/16
      vpc-template-body:
        description: CloudFormation template file path
        type: string
        default: file://cloudformation/TestVPC.yml
    #############################################################################
    docker:
      - image: cimg/aws:2023.04
    steps:
      - checkout
      # run aws-cli/setup with the installed orb
      # you need parameter below in steps "aws-cli/setup" for OIDC token  
      - aws-cli/setup:
          # required parameter
          role-arn: $AWS_ROLE_ARN
          # optional parameters
          aws-region: AWS_DEFAULT_REGION   
          profile-name: <<parameters.profile-name>>
          role-session-name: <<parameters.role-session-name>>
          session-duration: "1800"
      - run:
          name: Create vpc stack
          command: |
            aws cloudformation create-stack \
            --stack-name <<parameters.system-name>>-<<parameters.environment>>-vpc \
            --template-body <<parameters.vpc-template-body>> \
            --profile <<parameters.profile-name>> \
            --parameters ParameterKey=SystemName,ParameterValue=<<parameters.system-name>> \
                         ParameterKey=Environment,ParameterValue=<<parameters.environment>> ParameterKey=CidrBlock,ParameterValue=<<parameters.CidrBlock>> 
      - run:
          name: Wait until Stack is created
          command: |
            aws cloudformation wait stack-create-complete \
            --stack-name <<parameters.system-name>>-<<parameters.environment>>-vpc

workflows:
  cfn-test:
    jobs:
      - cfn-lint
      - aws-oidc-create-stack:
          # must use a valid CircleCI context if you need OIDC token
          context: aws
          requires:
            - cfn-lint
          # if you need parameters, you can change them below.(if you dont, CircleCI will use default parameters)
          system-name: rt
          environment: prod
          CidrBlock: 10.4.0.0/16

